#!/usr/bin/perl

use strict;

=head1 specs

Turns http://www.loc.gov/marc/bibliographic/ecbdist.html into the format
used by MARC::Lint.pm

Takes ecbdist.html as input.  Skips fixed fields and data marked
"[OBSOLETE]"  Also, the HTML file doesn't include the 841-88X tags,
so those are hardcoded here.

=head1 AUTHOR

Originally written by Colin Campbell at Sirsi, and taken over and modified
by Andy Lester.

=cut

open( my $fh, "../lib/MARC/Lint.pm" ) or die "Can't open module";
while ( <$fh> ) {
    print;
    last if /^__DATA__/;
}
close $fh;

my $in_tag = undef;
my $i;
my $i1;
my $i2;

my $v = 0;
while(<>) {
    unless ($v) {
	if (/010/) {
	    $v = 1;
	} else {
	    next;
	}
    }
    s/^ *//;
    if (/^(\d\d\d) -/) {
	my $tag = $1;
	if (/OBSOLETE/) { 
	    $in_tag = 0;
	    next; 
	}
	$in_tag = 1;
	if (/\(NR\)/) {
	    print "\n$tag\tNR\n";
	} else {
	    print "\n$tag\tR\n";
	}
	$i1 = $i2 = '';
	next;
    }
    if ($in_tag) {
	next if /OBSOLETE/;
	if (/^First/) {
	    $i = 1;
	} elsif (/^Second/) {
	    $i = 2;
	    if ($i1=~m/^#$/) {
		print "ind1\tblank\n";
	    } else {
		$i1=~s/#/b/;
		print "ind1\t$i1\n";
	    }
	} elsif (/^Subfield/) {
	    $i = 0;
	    if ($i2=~m/^#$/) {
		print "ind2\tblank\n";
	    } else {
		$i2=~s/#/b/;
		print "ind2\t$i2\n";
	    }
	} else {
	    if ($i) {
		next if /OBSOLETE/;
		my $data = '';
		if (/^(\d-\d)/) {
		    $data = $1;
		} elsif (/^[#0123456789]/) {
		    $data = substr($_, 0, 1);
		}
		if ($i == 1) {
		    $i1 .= $data;
		} elsif ($i == 2) {
		    $i2 .= $data;
		}

	    } else {
		next if /OBSOLETE/;
		if (/\$(.) -/) {
		    print "$1\t";
		    if (/\(R\)/) {
			print "R\n";
		    } else {
			print "NR\n";
		    }
		}
	    }
	}
    }
}

# Dump the hardcoded ones that aren't in the HTML file.
print <DATA>;

__END__
850	R
ind1	blank
ind2	blank
a	R
8	R

852	R
ind1	b012345678
ind2	b012
a	NR
b	R
c	R
e	R
f	R
g	R
h	NR
i	R
j	NR
k	R
l	NR
m	R
n	NR
p	NR
q	NR
s	R
t	NR
x	R
z	R
2	NR
3	NR
6	NR
8	NR

856	R
ind1	b012347
ind2	b0128
a	R
b	R
c	R
d	R
f	R
h	NR
i	R
j	NR
k	NR
l	NR
m	R
n	NR
o	NR
p	NR
q	NR
r	NR
s	R
t	R
u	R
v	R
w	R
x	R
y	R
z	R
2	NR
3	NR
6	NR
8	R

880	R
ind1	
ind2	
6	NR

887	R
ind1	blank
ind2	blank
a	NR
2	NR
