=encoding UTF-8

=head1 NAME

MARC-MiJ

=head1 DESCRIPTION

Allow perl's MARC::Record and MARC::File/MARC::Batch to deal with
marc-in-json, a MARC serialization described at
L<http://dilettantes.code4lib.org/blog/2010/09/a-proposal-to-serialize-marc-in-json/>.

=head1 EXAMPLES

    # Read in from newline-delimited JSON file
    use MARC::Batch;
    use MARC::File::MiJ;

    my $reader = new MARC::Batch('MiJ', $jsonfilename);
    while (my $r = $batch->next) { ... }


    # Convert binary to marc-in-json
    use MARC::Record::MiJ;
    my $batch = MARC::Batch->new('USMARC', 'file.mrc');
    open(my $jsonfile, '>', 'file.ndj' );
    while (my $r = $batch->next) {
      print $jsonfile MARC::Record::MiJ->to_mij($r), "\n";
    }
    close $jsonfile;

=head1 INSTALLATION

To install this module, run the following commands:

    perl Build.PL
    ./Build
    ./Build test
    ./Build install

=head1 LICENSE AND COPYRIGHT

Copyright (C) 2013 Bill Dueber

This software is free software and may be distributed under the same
terms as Perl itself. See the F<LICENSE> file included with this
distribution.

=cut
