#!/usr/bin/perl

use MARC::Record;

warn "Using MARC::Record v$MARC::Record::VERSION\n";

$/ = "`\n";
while (my $lifrec = <>) {
	my $marc = MARC::Record->new_from_microlif( $lifrec );
	warn $marc->title(), "\n";
	print $marc->as_usmarc();
}
